apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://63.180.183.215:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrakNDQVRlZ0F3SUJBZ0lJTG1SZ1BZQ2YrS3N3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOemc0T1RRME1qVTNNQjRYRFRJMk1Ea3dPVEEzTlRjek4xb1hEVEkzTURrdwpPVEEzTlRjek4xb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJPdmNwaUxSTWh2SnE5QXoKeGJ0YVorTExwWDg3ZksxcDFMV092TzNqWWRKV0ZrNk0ra1MxZWI2dStuOWdQb0xMWXVqWWU3Z0tTcnE3ejFPdQpOUGErMzM2alNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUW9OOUE1QllIZlZlc0RYNlFsRWdhbEF6S0tyVEFLQmdncWhrak9QUVFEQWdOSkFEQkcKQWlFQXRKTTNadVhNenUwUnQzc3hnZkwzZEp5T2hObWwzMmcwTVZ6RHhLRVI1akFDSVFDSEl6S2FyTFpwTTU5Rgp4bFJzcHVXVE1NU0pTZkVqNFQyMGkwWXFQTGZJT2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCZHpDQ0FSMmdBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwClpXNTBMV05oUURFM09EZzVORFF5TlRjd0hoY05Nall3T1RBNU1EYzFOek0zV2hjTk16WXdPVEEyTURjMU56TTMKV2pBak1TRXdId1lEVlFRRERCaHJNM010WTJ4cFpXNTBMV05oUURFM09EZzVORFF5TlRjd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBVFgwNXVxaXFFMnJReVFUNDM3a2dGWWN5d3RLdHdZV1ljd1NEcDV6MDBMCmRWKzVuSXczclBPbHFJWUhLN0owUzlNTTNXaDE2Smlua0lZSHgzcFBGWGkzbzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVLRGZRT1FXQjMxWHJBMStrSlJJRwpwUU15aXEwd0NnWUlLb1pJemowRUF3SURTQUF3UlFJZ1cvOUZ6c3F0TlYycEtDNUNVRjh2d2o4d0MvNzh0OUNpCldRNDRsQ0xjRk1rQ0lRRE5Tc0UvNXk5S05oS0kwVGVaSmF2SW1NenVVT1pneVJNUUZ2MkJUT3BXSUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUpSVWVncm1aSE9DcXh1RmxBaDBPWEYvM2R0OXNxVVp3NFlIalR0bklPb0xvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFNjl5bUl0RXlHOG1yMERQRnUxcG40c3VsZnp0OHJXblV0WTY4N2VOaDBsWVdUb3o2UkxWNQp2cTc2ZjJBK2dzdGk2Tmg3dUFwS3VydlBVNjQwOXI3ZmZnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
